version: '3'
services:
  pg:
    image: "postgres"
    ports:
    - 54322:5432
    env_file:
      - database.env
    volumes:
      - ./init_postgresql.sql:/docker-entrypoint-initdb.d/init.sql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 54333:3306
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./init_mysql.sql:/docker-entrypoint-initdb.d/init.sql